import { SiteConfig } from "./types";

export const config: SiteConfig = {
  profile: {
    name: "Binary Ash",
    title: "Full-Stack, AI & Embedded Engineer",
    avatar: "/image.png",
    email: "binaryash@hotmail.com",
    bioFile: "/content/profile/bio.md",
    skills: [
      "Python",
      "JavaScript",
      "SQL",
      "Git",
      "Linux",
      "Azure",
      "Docker",
      "CI/CD",
      "React.js",
      "Django",
      "FastAPI",
      "Node.js",
      "GenAI",
      "LLMs",
      "RAG",
      "AI Agents",
      "LangChain",
      "Transformers",
      "PyTorch",
      "TensorFlow",
      "PostgreSQL",
      "Redis",
      "Celery",
    ],
    socials: [
      {
        platform: "GitHub",
        url: "https://github.com/binaryash",
        icon: "Github",
      },
      {
        platform: "LinkedIn",
        url: "https://www.linkedin.com/in/ash-c-7b3113291",
        icon: "Linkedin",
      },
      {
        platform: "Resume",
        url: "/ash-resume.pdf",
        icon: "FileText",
      },
    ],
  },
  projects: [
    {
      id: "redbud-ems",
      title: "Redbud - Employee Management System",
      shortDescription: "Workforce platform with Gemini agents for contract assignment and RAG-based matching.",
      coverImage: "https://picsum.photos/800/600?random=11",
      date: "2024",
      featured: true,
      tags: ["Django", "React", "GenAI", "AI Agents", "RAG"],
      contentFile: "/content/projects/redbud-ems.md",
      links: {
        repo: "https://github.com/binaryash/redbud",
      },
    },
    {
      id: "genai-foundation-models",
      title: "GenAI and Foundation Models",
      shortDescription: "From-scratch implementations of Transformers and GANs for NLP and Vision.",
      coverImage: "https://picsum.photos/800/600?random=12",
      date: "2024",
      featured: true,
      tags: ["Transformers", "GAN", "MLOps", "GenAI", "ML"],
      contentFile: "/content/projects/genai-foundation-models.md",
      links: {
        repo: "https://github.com/binaryash/ml",
      },
    },
    {
      id: "job-fetcher",
      title: "Job Fetcher",
      shortDescription: "AI-powered job aggregator with automated extraction and resume generation.",
      coverImage: "https://picsum.photos/800/600?random=13",
      date: "2024",
      featured: true,
      tags: ["Python", "Django", "GenAI", "Web Scraping", "Next.js", "AI Agents"],
      contentFile: "/content/projects/job-fetcher.md",
      links: {
        repo: "https://github.com/binaryash/job-fetcher",
      },
    },
    {
      id: "async-task-manager-v2",
      title: "Asynchronous TaskManager",
      shortDescription: "Distributed data scraping and summarization using Celery, Redis, and GenAI.",
      coverImage: "https://picsum.photos/800/600?random=14",
      date: "2023",
      featured: true,
      tags: ["Django REST", "Celery", "Redis", "GenAI", "MCP"],
      contentFile: "/content/projects/async-task-manager-v2.md",
      links: {
        repo: "https://github.com/binaryash/taskmanager",
      },
    },
    {
      id: "college-management-system",
      title: "College Management System",
      shortDescription:
        "Full-stack college management platform with Django backend and React frontend.",
      coverImage: "https://picsum.photos/800/600?random=1",
      date: "2024",
      featured: false,
      tags: ["Django", "React.js", "Python"],
      contentFile: "/content/projects/college-management-system.md",
      links: {
        demo: "https://college-frontend-liard.vercel.app/",
        repo: "https://github.com/binaryash/college-management-system",
      },
    },
    {
      id: "realtime-chat-app",
      title: "Real-Time Chat Application",
      shortDescription:
        "Real-time chat application using Django Channels and WebSockets.",
      coverImage: "https://picsum.photos/800/600?random=2",
      date: "2024",
      featured: false,
      tags: ["Django", "Django Channels", "WebSockets"],
      contentFile: "/content/projects/realtime-chat-app.md",
      links: {
        repo: "https://github.com/binaryash/django-chat-app",
      },
    },
    {
      id: "event-management-mern",
      title: "Event Management Application",
      shortDescription:
        "MERN-stack event management app for creating and managing events.",
      coverImage: "https://picsum.photos/800/600?random=3",
      date: "2023",
      featured: false,
      tags: ["MongoDB", "Express.js", "React.js", "Node.js"],
      contentFile: "/content/projects/event-management-mern.md",
      links: {
        repo: "https://github.com/binaryash/event-management-application",
      },
    },
    {
      id: "rag-project",
      title: "RAG Project",
      shortDescription:
        "Retrieval-Augmented Generation pipeline with MiniLM and GPT-2.",
      coverImage: "https://picsum.photos/800/600?random=4",
      date: "2023",
      featured: false,
      tags: ["MiniLM", "GPT-2", "FAISS"],
      contentFile: "/content/projects/rag-project.md",
      links: {
        repo: "https://github.com/binaryash/ml/blob/main/unnamed/RAG_Project.ipynb",
      },
    },
    {
      id: "movie-recommendation",
      title: "Movie Recommendation System",
      shortDescription:
        "Hybrid movie recommender with neural networks and collaborative filtering.",
      coverImage: "https://picsum.photos/800/600?random=5",
      date: "2023",
      featured: false,
      tags: ["Neural Networks", "Hybrid Filtering"],
      contentFile: "/content/projects/movie-recommendation.md",
      links: {
        repo: "https://github.com/binaryash/ml/blob/main/unnamed/movie_recommendation.ipynb",
      },
    },
    {
      id: "invoice-generator",
      title: "Invoice Generator",
      shortDescription:
        "Clean, responsive invoice generator built with React and Ant Design.",
      coverImage: "https://picsum.photos/800/600?random=6",
      date: "2023",
      featured: false,
      tags: ["React.js", "Vite", "Ant Design"],
      contentFile: "/content/projects/invoice-generator.md",
      links: {
        demo: "https://invoice-generator-theta-one.vercel.app/",
      },
    },
    {
      id: "async-task-manager",
      title: "Asynchronous Task Manager",
      shortDescription:
        "Django-based task manager with Celery and Redis for background processing.",
      coverImage: "https://picsum.photos/800/600?random=7",
      date: "2022",
      featured: false,
      tags: ["Celery", "Redis", "Django"],
      contentFile: "/content/projects/async-task-manager.md",
      links: {
        repo: "https://github.com/binaryash/taskmanager",
      },
    },
    {
      id: "shopify-mern",
      title: "Shopify MERN App",
      shortDescription:
        "MERN application showcasing Shopify-like product catalog functionality.",
      coverImage: "https://picsum.photos/800/600?random=8",
      date: "2022",
      featured: false,
      tags: ["MongoDB", "Express.js", "React.js", "Node.js"],
      contentFile: "/content/projects/shopify-mern.md",
      links: {
        repo: "https://github.com/binaryash/shopify_product_showcase",
      },
    },
  ],
  blog: [
    {
      id: "ai-agents-orchestration",
      title: "Orchestrating Intelligence: The Rise of AI Agents",
      excerpt: "Exploring multi-agent systems, tool-use patterns, and the Model Context Protocol (MCP).",
      date: "Feb 05, 2026",
      readTime: "7 min read",
      tags: ["AI Agents", "Orchestration", "MCP", "LangGraph"],
      contentFile: "/content/blog/ai-agents-orchestration.md",
    },
    {
      id: "demystifying-genai",
      title: "Demystifying Generative AI: From Transformers to Production",
      excerpt: "A deep dive into self-attention, embeddings, and the engineering challenges of shipping AI.",
      date: "Jan 20, 2026",
      readTime: "6 min read",
      tags: ["GenAI", "Transformers", "LLMs", "RAG"],
      contentFile: "/content/blog/demystifying-genai.md",
    },
    {
      id: "web-development-journey",
      title: "My Journey Through Full-Stack Development",
      excerpt:
        "From Django to MERN: exploring different tech stacks and finding what works best.",
      date: "Nov 15, 2024",
      readTime: "5 min read",
      tags: ["Web Development", "Django", "MERN"],
      contentFile: "/content/blog/web-development-journey.md",
    },
    {
      id: "machine-learning-web-dev",
      title: "Integrating Machine Learning into Web Applications",
      excerpt:
        "Practical approaches to bringing ML models from notebooks to production web apps.",
      date: "Oct 28, 2024",
      readTime: "6 min read",
      tags: ["Machine Learning", "FastAPI", "Production"],
      contentFile: "/content/blog/machine-learning-web-dev.md",
    },
    {
      id: "low-level-programming",
      title: "Why C++ Still Matters for Web Developers",
      excerpt:
        "Understanding memory management and performance optimization through low-level programming.",
      date: "Sep 22, 2024",
      readTime: "4 min read",
      tags: ["C++", "Performance", "Optimization"],
      contentFile: "/content/blog/low-level-programming.md",
    },
  ],
};